name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted, macOS, ARM64]
    env:
      RUNNER_TOOL_CACHE: /Users/guruprasad/.cache/hostedtoolcache
      RUNNER_TEMP: /Users/guruprasad/.cache/runner_temp    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up Virtual Environment
      run: python -m venv .venv

    - name: Activate Virtual Environment
      run: source .venv/bin/activate

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run Ruff lint check
      run: poetry run ruff check --exit-non-zero-on-fix .
